name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  
jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: instalando dependencias
      run: pip install -r requirements.txt
    - name: ejecutando pruebas
      run: python manage.py test
   
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_KEY }}
      - name: notificar a slack
        uses: act10ns/slack@v2
        with:
          channel: '#todo-feedback-ci'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
