name: CI
on: 
  push: 
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
    - uses: actions/checkout@v4
    - name: instalando dependencias
      run: pip install -r requirements.txt
    - name: ejecutando pruebas
      run: python manage.py test
    - name: deploy
      run: curl -X POST "https://api.render.com/deploy/srv-d0vh3qh5pdvs738h668g?key=bDoS68SgEpM"
    - uses: act10ns/slack@v2
      with:
        channel: '#todo-feedback-ci'
        status: ${{job.status}}
        steps: ${{toJson(steps)}}
      if: always()
      
