name: CI
on: 
  push: 
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: probando
      run: pip install -r requirements.txt
    - name: probando2
      run: python manage.py
