name: CI
on: 
  push: 
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: instalando dependencias
      run: pip install -r requirements.txt
    - name: ejecutando pruebas
      run: python manage.py test
